import type { Metadata } from "next"
import { Cormorant_Garamond, Poppins } from "next/font/google"
import "./globals.css"

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
  weight: ["400"],
})

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Header Component that contains both Logo and Navigation
const Header = () => {
  const navItems = [
    { name: 'Home', href: '/' },
    { name: 'Projects', href: '/projects' },
    { name: 'Lab', href: '/lab' },
    { name: 'Blog', href: '/blog' },
    { name: 'About', href: '/about' },
    { name: 'Contact', href: '/contact' }
  ];

  return (
    <header className="fixed top-0 left-1/2 transform -translate-x-1/2 z-50 py-6 w-full max-w-6xl">
      <div className="flex items-center justify-between bg-black/25 px-6 h-22">
        {/* Logo */}
        <div>
          <a href="/" className="block">
            <img
              src="/Kairobotics-nobg.png"
              alt="Kairobotics Logo"
              className="w-40 h-auto hover:opacity-80 transition-opacity duration-200"
            />
          </a>    
        </div>

        {/* Navigation */}
        <nav>
          <ul className="flex space-x-6">
            {navItems.map((item) => (
              <li key={item.name}>
                <a
                  href={item.href}
                  className="text-white hover:text-neutral-300 font-medium text-base tracking-wide transition-colors duration-200 relative group"
                >
                  {item.name}
                  <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-white transition-all duration-300 group-hover:w-full"></span>
                </a>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
};

// Footer Component
const Footer = () => {
  const currentYear = new Date().getFullYear();
  
  return (
    <footer className="bg-black/90 text-white py-8 mt-16">
      <div className="max-w-6xl mx-auto px-6">
        <div className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
          <div className="text-center md:text-left">
            <p className="text-sm text-neutral-300">
              © {currentYear} Kairobotics. All rights reserved.
            </p>
          </div>
          
          <div className="text-center md:text-right">
            <p className="text-sm text-neutral-300">
              Made with{" "}
              <a 
                href="https://nextjs.org" 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-white hover:text-neutral-300 transition-colors duration-200 underline decoration-1 underline-offset-2"
              >
                Next.js
              </a>
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.variable} ${poppins.variable} bg-neutral-100`}
      >
        {/* Header with Logo and Navigation wrapped together */}
        <Header />
        
        {/* Your page content goes here */}
        <main className="pt-20 md:pt-24 lg:pt-28">
          {children}
        </main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  )
}